Feat/create-menu-side-bar
Grupo-GCB/expense-tracker-portal pull request #11
Opened 2023-08-15 03:05 UTC by AugustoCVS

# Criação do menu latarel buscando as informações do usuário, todos os testes e documentação.

Solicitante(s) da tarefa

- Kayke Fujinaka

Card(s) da tarefa

- [[Front-end] Navegação do Menu Lateral](https://dev.azure.com/GCBInvestimentos/Academy%202.0/_sprints/taskboard/Academy%202.0%20Team/Academy%202.0/Sprint%202?workitem=22933)

- [[Front-end] Buscar os Dados do Usuário no Menu Lateral](https://dev.azure.com/GCBInvestimentos/Academy%202.0/_sprints/taskboard/Academy%202.0%20Team/Academy%202.0/Sprint%202?workitem=22932)

# Checklist

Você realizou o code review do seu próprio PR?

- [X] Sim
- [ ] Não

---

Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?

- [ ] Sim
- [X] Não

### Testes que precisa ser realizado para aprovação do PR

- [X] Produtos
- [ ] Ux/Ui
- [ ] QA

Responsáveis pelos testes QA:

- Charlene Fialho

2023-08-15 04:52 UTC, Diogo-gallina requested changes

2023-08-15 04:52 UTC, Diogo-gallina commented on src/app/layout.tsx
> +          {children}</body>
formatar o código

2023-08-15 04:52 UTC, Diogo-gallina commented on src/app/page.tsx
>          <Home user={user} />
formatar código, todas chaves tem um espaço no começo e um no final

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/Home/index.tsx
> +    <div className='lg:ml-28'>Welcome {user.name}!</div>
formatar chaves

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/MenuSideBar.stories.tsx
> +  <UserProvider user={user}>
formatar todo esse teste com prettier

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/components/Header/index.tsx
> +        alt={open ? "Logo da GCB." : "Metade da cabeça do touro da GCB."}
formatar

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/components/Header/index.tsx
> +import logoGCB from "@/app/assets/svg/logo.svg";
barrel export

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/components/MenuUser/index.tsx
> +          {open && <span>Configurações</span>}
formatar

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/components/UserProfile/UserProfile.spec.tsx
> +    const { container } = render(<UserProfile open={true} />);
formatar

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/components/UserProfile/UserProfile.stories.tsx
> +  withUserProvider(() => <UserProfile {...args} />, defaultUser);
formatar

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/components/UserProfile/index.tsx
> +            src={user.picture}
formatar

2023-08-15 04:52 UTC, Diogo-gallina commented on src/components/MenuSideBar/index.tsx
> +      <button onClick={handleDestroyUserToken}>
formatar o arquivo

2023-08-15 11:18 UTC, AugustoCVS commented on src/components/MenuSideBar/components/Header/index.tsx
> +import logoGCB from "@/app/assets/svg/logo.svg";
Eu preciso confirmar com alguem, mas eu acho que como eu coloco um nome específico para cada imagem assim que eu importo, não tem como eu colocar um barrel export, não reconhece

2023-08-15 11:20 UTC, AugustoCVS commented on src/app/page.tsx
>          <Home user={user} />
Por causa das mudanças que a gente vai fazer no projeto esse arquivo vai deixar de existir quand a Charlene subir o PR dela, então vou deixar sem a alteração

2023-08-15 11:22 UTC, AugustoCVS commented on src/components/MenuSideBar/MenuSideBar.stories.tsx
> +  <UserProvider user={user}>
Mas ta formatado com o prettier

2023-08-15 11:23 UTC, AugustoCVS commented on src/components/MenuSideBar/components/Header/index.tsx
> +        alt={open ? "Logo da GCB." : "Metade da cabeça do touro da GCB."}
ta formatado, essa foi a formatação do prettier

2023-08-15 17:48 UTC, Kayke-Fujinaka requested changes

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +describe("MenuSideBar", () => {
Mudar a descrição para "Sidebar Menu".

Ambos os nomes não estão errados, porém creio que o mais correto e o que define o que você desejava expressar seja o de cima, pois ele está referenciando que o menu é uma barra lateral.

Pensa nesse exemplo:
- Red car: O carro é vermelho 😁
- Car red: O vermelho é carro ❌

Além disso, é necessário mudar o nome do componente e tudo que tenha o nome atual "MenuSideBar" para "SidebarMenu" ou simplesmente "Sidebar" (caso coloque esse é só colocar "Sidebar" na descrição do teste) que é bem direto ao ponto.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to toggle sidebar when List icon is clicked", () => {
"should be able to toggle sidebar when the hamburguer menu is clicked"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +    const menuHamburguer = screen.getByTestId("menuHamburguer");
Mesma coisa do comentário de cima do "MenuSideBar".

Em inglês, os adjetivos geralmente precedem os substantivos que modificam, como no exemplo do "red car".

O correto seria "Hamburguer Menu".

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +    expect(screen.getByTestId("menuNav")).toHaveClass("sm:w-full");
Mesma coisa que os comentários acima "navigationMenu" ou "navMenu".

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to close sidebar when X icon is clicked", () => {
"should be able to close sidebar when the close icon is clicked"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +    const closeX = screen.getByTestId("closeX");
Não vejo sentido nessa nomenclatura "closeX" para o ID e variável.

Creio que tenham melhores opções como apenas "close". Eu sei que o "X" é o ícone de fechar, mas não agrega tanta relevância para esta nomenclatura.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to render user profile with picture and name", () => {
"should be able to render the user's profile with a picture and name"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to destroy user token when SignOut button is clicked", () => {
"should be able to destroy the user token when the Sign Out button is clicked"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +    const signOutButton = screen.getByTestId("singOut");
"signOut"

"Sing" é cantar.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to render flex layout when user is logged in", () => {
"should be able to display a flex layout when the user is logged in"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to render hidden layout when user is not logged in", () => {
"should be able to display a hidden layout when the user is not logged in"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/MenuSideBar.spec.tsx
> +  it("should be able to render all components correctly when user is logged in", () => {
"should be able to render all components correctly when the user is logged in"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/Header.spec.tsx
> +  it("shoulde be able to render open header with the correct image", () => {
"should be able to render an open header with the correct image"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/Header.spec.tsx
> +  it("shoulde be able to render closed header with the correct image", () => {
"should be able to render a closed header with the correct image"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/Header.spec.tsx
> +      name: "Metade da cabeça do touro da GCB.",
A GCB não tem o ícone de um touro por completo. É sempre apenas a metade da cabeça, sendo assim, a descrição poderia ser "Ícone do touro do Grupo GCB"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/Header.spec.tsx
> +    const image = screen.getByRole("img", { name: "Logo da GCB." });
"Logo do Grupo GCB"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/index.tsx
> +import logoGCB from "@/app/assets/svg/logo.svg";
"gcbLogo"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/index.tsx
> +import logoBull from "@/app/assets/svg/logoBull.svg";
"bullIcon"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/index.tsx
> +        alt={open ? "Logo da GCB." : "Metade da cabeça do touro da GCB."}
"Logo do Grupo GCB" e "Ícone do touro do Grupo GCB"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/Header/index.tsx
> +export function Header({ open }: IMenuProps) {
Siga o padrão da nomenclatura das outras interfaces.

"IMenu"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +  it("it should be able to render the menu options with correct icons and labels", () => {
Tirar o "it"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +  it("it should be able to render the menu options with correct icons and labels", () => {
"should be able to render the menu options with the correct icons and labels"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +  it("should be able to render correct style in icons when open prop is true", () => {
"should be able to render the correct styles for icons when the open prop is true"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +  it("should be able to render correct style in icons when open prop is false", () => {
"should be able to render the correct styles for icons when the open prop is false"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/interfaces/UserProfileProps.tsx
> +export interface IUserProfileProps{
"IUserProfile"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/interfaces/UserProfileProps.tsx
> +import { IUser } from ".";
Organizar os imports.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +    const resumoIcon = screen.getByTestId("resumoIcon");
Mudar em todos para "summaryIcon"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +    const homeLabel = screen.getByText("Home");
Mudar em todos os abaixo "...LabelText"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/MenuOptions.spec.tsx
> +    const carteirasIcon = screen.getByTestId("carteirasIcon");
Mudar em todos para "walletsIcon"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuOptions/index.tsx
> +        </li>
Essas `<li>` possuem a mesma estilização e estrutura em todo o componente do MenuOptions, a qual não entra no conceito do DRY (Don't Repeat Yourself".

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/MenuUser.spec.tsx
> +describe("MenuUser", () => {
"User Menu"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/MenuUser.spec.tsx
> +  it("should be able to render menu user with correct icons when open prop is true", () => {
"should be able to render the user menu with the correct icons when the open prop is true"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/MenuUser.spec.tsx
> +  it("should be able to render menu user with correct icons when open prop is false", () => {
"should be able to render the user menu with the correct icons when the open prop is false"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/MenuUser.spec.tsx
> +    const notificacoesIcon = screen.getByTestId("notificacoesIcon");
"notificationsIcon"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/MenuUser.spec.tsx
> +    const notificacoesLabel = screen.getByText("Notificações");
"...LabelText"

Mudar em todos.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/MenuUser.spec.tsx
> +    const configuracoesIcon = screen.getByTestId("configuracoesIcon");
"configurationsIcon"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/index.tsx
> +export function MenuUser({ open }: IMenuProps) {
"UserMenu"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/MenuUser/index.tsx
> +        </li>
É praticamente a mesma lista. 

A única coisa que muda é o w-60 e w-56. Porém, é válido evitar as mesmas estilizações e linhas de código.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/UserProfile/UserProfile.spec.tsx
> +  it("should be able to render user profile with picture and name", () => {
"should be able to render user's profile with a picture and name"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/UserProfile/UserProfile.spec.tsx
> +  it("should be able to apply correct styles when open is true", () => {
"should be able to apply the correct styles when open is true."

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/UserProfile/UserProfile.spec.tsx
> +  it("should be ablt to apply correct styles when open is false", () => {
"should be able to apply the correct styles when open is false."

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/UserProfile/index.tsx
> +      <p className="flex text-white text-base">{user?.name}</p>
Desestrutura o name e picture logo abaixo do user na linha 7.

"const { picture, name } = user"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/components/UserProfile/index.tsx
> +        user.picture.trim() !== "" && (
Separa isso em uma variável.

`const isPictureValid = picture && typeof picture === "string" && picture.trim() !== "";`

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/index.tsx
> +export function MenuSideBar() {
"Sidebar"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/index.tsx
> +  const [open, setOpen] = useState(false);
Tipar o estado para boolean

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/index.tsx
> +  }, [handleMenuResize]);
Coloca ele logo abaixo do `useUser()`

```
  useEffect(() => {
    adjustMenuOnResize();
    window.addEventListener("resize", adjustMenuOnResize);
    return () => {
      window.removeEventListener("resize", adjustMenuOnResize);
    };
  }, []);
```

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/index.tsx
> +  };
"handleMenuOnResize"

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/index.tsx
> +      </button>
É inapropriado ter um link dentro de um botão, e, além disso, o botão não possui um atributo type especificado nem uma ação definida para quando for clicado. Se a razão for puramente estética, considere aplicar os estilos diretamente ao link e remover o botão. Se a necessidade for de um botão, você pode redirecionar para a página desejada através da função onclick do botão.

2023-08-15 17:48 UTC, Kayke-Fujinaka commented on src/components/MenuSideBar/index.tsx
> +  return (
Aplicar HTML Semântico!

2023-08-15 22:37 UTC, AugustoCVS commented on src/components/MenuSideBar/components/UserProfile/index.tsx
> +      <p className="flex text-white text-base">{user?.name}</p>
Tentei, não funcionou, acho que por ser do auth0 deve ter um funcionamento um pouco diferente

2023-08-15 22:42 UTC, AugustoCVS commented on src/components/MenuSideBar/components/UserProfile/index.tsx
> +        user.picture.trim() !== "" && (
Desse jeito especificamente não funcionou, tive que fazer algumas alterações

2023-08-15 23:51 UTC, Kayke-Fujinaka requested changes

2023-08-15 23:51 UTC, Kayke-Fujinaka commented on src/components/Sidebar/components/Header/index.tsx
> +import bullIcon from "@/app/assets/svg/logoBull.svg";
Mudar o nome do SVG

2023-08-15 23:51 UTC, Kayke-Fujinaka commented on src/components/Sidebar/components/UserProfile/UserProfile.stories.tsx
> +import { IUserProfileProps } from "@/interfaces";
Muda o nome dessa interface tirando esse "Props"

2023-08-16 10:41 UTC, Kayke-Fujinaka approved these changes

2023-08-16 10:58 UTC, Kayke-Fujinaka approved these changes

2023-08-16 12:47 UTC, mdmath15 approved these changes

2023-08-16 13:06 UTC, Santosl2 approved these changes

2023-08-16 13:13 UTC, RodrigoSaantos approved these changes

2023-08-16 16:42 UTC, charlenefialho approved these changes

2023-08-16 17:04 UTC, Diogo-gallina requested changes

2023-08-16 17:04 UTC, Diogo-gallina commented on package.json
> +    "tailwind-scrollbar": "^3.0.5",
Mudar versão do package json quando instalar ou retirar alguma dependência

2023-08-16 17:04 UTC, Diogo-gallina commented on src/app/layout.tsx
>  import { Inter } from 'next/font/google'
Alterar todos imposts ou para aspas simples, ou para aspas duplas.

2023-08-16 17:04 UTC, Diogo-gallina commented on src/components/index.ts
>  export * from './Button'
Alterar todos imports para aspas duplas ou simples

2023-08-16 17:04 UTC, Diogo-gallina commented on src/interfaces/index.tsx
> +export * from './UserProfile'
Alterar todos imports para aspas duplas ou simples

2023-08-16 17:12 UTC, Diogo-gallina approved these changes

2023-08-16 17:16 UTC, merged