Feat/landing page
Grupo-GCB/expense-tracker-portal pull request #5
Opened 2023-07-28 20:35 UTC by charlenefialho

# Descrição da tarefa
Criei stories de cada componente para o storybook e implementei teste unitários na landing page e componentes.

Solicitante(s) da tarefa

- Implementar testing-library e storybook da landing-page

Card(s) da tarefa

- [Implementar testing-library e storybook da landing-page](https://dev.azure.com/GCBInvestimentos/Academy%202.0/_workitems/edit/22488)

# Checklist

Você realizou o code review do seu próprio PR?

- [X] Sim
- [ ] Não

---

Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?

- [ ] Sim
- [X] Não

### Testes que precisa ser realizado para aprovação do PR

- [X] Produtos
- [ ] Ux/Ui
- [ ] QA

Responsáveis pelos testes QA:

- Augusto Santana

2023-07-28 21:35 UTC, Kayke-Fujinaka commented on .storybook/preview.ts
> +import "../src/styles/tailwind.css";
Não deu para aplicar path mapping, né? 

Não conseguem validar se realmente não dá? O pessoal de back tinha comentado que não era possível na nova versão do TypeORM, mas conseguiram desenrolar.

2023-07-28 21:36 UTC, Kayke-Fujinaka commented on .storybook/preview.ts
> +};
O que seria isso?

2023-07-28 21:45 UTC, charlenefialho commented on .storybook/preview.ts
> +};
É uma config de viewport personalizada

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/Button/Button.spec.tsx
> +    const button = screen.getByRole("button", { name: buttonText });
Utilize o testID ou data-testid para busca a referencia do elemento que deseja. 
É mais preciso sem chances de erros.

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/Button/Button.spec.tsx
> +    expect(button).toBeInTheDocument();
Seu teste "should be able to render the children correctly"
Mas de fato não esta validando isso. 
Você disse que esperava que renderiza-se um children no botão, mas nenhum momento verificou se o children estava lá.

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/Button/Button.spec.tsx
> +  afterEach(cleanup);
Verifique a necessidade do AfterEach. 
Ambos os testes não compartilham nenhuma configuração ou dependência em comum.

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/Button/Button.spec.tsx
> +    render(<Button onClick={handleClick}>Clique aqui</Button>);
Segue um padrão, poderia jogar a variável de cima no topo, e utilizar a mesma para ambos components.

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const logo = screen.getByAltText("logo gcb");
Isso aqui, Okay

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const logo = screen.getByAltText("logo gcb");
Porem atenção.

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const title = screen.getByText(
Okay, tbm ficando um pouco de atenção. 
Nesse cenário tudo bem, mas esse teste n garante muita coisa.

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const button = screen.getByRole("button");
Isso aqui, só fala que existe um botão. 
Que botão e esse ? 
O que ele faz ? 
É Clicavel ? 
O que acontece quando clica? 
"Existe na tela, só isso que o teste sabe."

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const image = screen.getByAltText("home do site");
Existe um ALT. 
Blz, mas o que ele é ?

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const image = screen.getByAltText("home do site");
A constante fala que é uma imagem, mas o teste garante isso ?

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const buttonText = screen.getByRole("button", { name: "Experimentar!" });
Pegue a referencia pelo testeID assim fica generico, se existe 2 botões com o name "Experimentar!" ?

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/LandingPage.spec.tsx
> +    const linkButton = screen.getByRole("link", { name: "Experimentar!" });
Esse aqui, tudo bem fazer assim. Garantiu que é um link, tem um name e depois validou o "href".
Acho válido!

2023-07-28 22:31 UTC, cleversonffaria commented on src/components/LandingPage/index.tsx
> +                <Button className="py-2 px-4  hover:bg-green-300 md:w-64 md:items-self-center rounded-md bg-green-500 md:py-4  md:px-3">
Se o buttom é um component !

Por que existe tantas regras de estilização para ele. 
Trabalhe com variantes se necessário. 

Não sei se utiliza essa mesma estilização em outros botões. Caso acontece isso só reforça o que falei.  

Caso não utilize em outros fluxos. É factivel fazer assim porem atenção. Pra n replicar códigos atoa.

2023-07-29 00:13 UTC, Kayke-Fujinaka requested changes

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on package.json
> +    "axios": "^1.4.0",
O axios não é dependência de desenvolvimento.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/app/assets/img/imagem-site.png
É válido colocar uma imagem .webp, @cleversonffaria?

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/index.tsx
> +          <Image className="h-11 " src={logo} alt="logo gcb" />
alt="Logo da Grupo GCB"

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.spec.tsx
> +import React from "react";
Organizar o import

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/Header.stories.tsx
> +import { Header } from "./index";
Não precisa passar o index no path.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.stories.tsx
> +import { LandingPage } from "./index";
Não precisa passar o index.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +import Link from "next/link";
Organizar o import.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +                <Button className="py-2 px-4  hover:bg-green-300 md:w-64 md:items-self-center rounded-md bg-green-500 md:py-4  md:px-3">
Arrumar identação.

Tem 2 espaços entre as estilizações.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +      <Header/>
Arrumar identação. 

`<Header />`

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
>        <main className="w-full min-h-screen bg-gray-300 font-roboto font-semibold text-white xl:-mt-1">
Não seria válido passar o `font-roboto` de maneira geral no projeto? 

Não sei se é a melhor prática, mas não é viável deixar essas estilizações de estilização do texto nas tag que são relacionadas a texto, como, por exemplo: `heading`, `paragraph`,...

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.stories.tsx
> +      defaultViewport: "laptopLarge",
Não exite um `defaultViewport` para laptop?

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.stories.tsx
> +};
Deixa acima do Mobile para deixar na ordem.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.stories.tsx
> +  title: "Components/LandingPage",
Seria um componente uma página?

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/Header.stories.tsx
> +};
Deixa acima no `Mobile`

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/Header.stories.tsx
> +export const Desktop: StoryObj = {};
Define o tamanho como laptop

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/Button/Button.spec.tsx
> +    const buttonText = "Clique aqui";
Não tem sentido você ter criado uma variável aqui e não ter compartilhado com o teste de baixo que tem a mesma mensagem.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/Button/Button.spec.tsx
> +  it("should be able to call onClick function when the button is clicked", () => {
"should be able to click the button"

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/Button/Button.stories.tsx
> +    className:
Arruma a identação.

2023-07-29 00:13 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.spec.tsx
> +describe("LandingPage", () => {
Landing Page

2023-07-29 00:23 UTC, AdilsonOliveira37 commented on src/components/LandingPage/index.tsx
> +                  <Link href="/api/auth/login" className="text-sm md:text-2xl ">
Não faz sentido um link dentro de um botão, e o botão também não esta especificado seu type nem a ação ao ser clicado.
Se for só por conta de estilização, aplique elas ao link e exclua o botão.
Se precisar de ser um botão, uma alternativa é na função de onclick do botão, executar o redirecionamento para a página que você quer.

2023-07-29 02:24 UTC, Kayke-Fujinaka commented on src/components/Button/Button.spec.tsx
> +import { cleanup, fireEvent, render, screen } from "@testing-library/react";
Vê depois essa questão do eslint que não está pegando quando você formata o código.

2023-07-29 02:35 UTC, Kayke-Fujinaka commented on src/app/assets/img/imagem-site.png
Muda o nome desse arquivo.

portal.png

2023-07-29 03:01 UTC, Kayke-Fujinaka requested changes

2023-07-29 03:01 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/index.tsx
>            <span className="h-11 pt-1 flex items-center justify-center ">
Tira esse pt-1

2023-07-29 03:01 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
>                      Experimentar!
Quando clicar no botão de experimentar colocar algum loading indicando para o usuário que está carregando, e impedir ele de ficar clicando 1001x no botão igual um maluco.

2023-07-29 03:01 UTC, Kayke-Fujinaka commented on package.json
>      "@auth0/nextjs-auth0": "^3.0.0-beta.3",
Atualiza a versão do package.json quando mexer nele.

2023-07-29 03:01 UTC, Kayke-Fujinaka commented on src/components/Button/Button.stories.tsx
> +};
Não tem um hover na estilização.

2023-07-29 03:01 UTC, Kayke-Fujinaka commented on src/components/Button/Button.stories.tsx
> +export const Big: StoryObj<IButtonProps> = {
Acho válido ter apenas um que o usuário que esteja mexendo na documentação do storybook possa ter o controle de escolher qual botão ele quer em específico, ou seja, alterar as cores, texto, tamanho (small, medium e big) e etc.

2023-07-31 21:21 UTC, shimarrudz requested changes

2023-07-31 21:21 UTC, shimarrudz commented on package.json
Não seria viável atualizar a versão do package por conta das instalações?

2023-07-31 21:21 UTC, shimarrudz commented on src/components/LandingPage/Header/Header.stories.tsx
> +import { Header } from "./index";
Seria possível aplicar path maping ou export barrel aqui?

2023-07-31 21:21 UTC, shimarrudz commented on src/components/LandingPage/Header/index.tsx
> +import logo from "../../../app/assets/svg/logo.svg";
Voltar para path maping

2023-07-31 21:21 UTC, shimarrudz commented on src/components/LandingPage/LandingPage.spec.tsx
> +import { LandingPage } from ".";
dar um "enter" entre a linha 2 e a linha 3, ex:

import React from "react";
import { render, screen } from "@testing-library/react";

import { LandingPage } from ".";

2023-07-31 21:21 UTC, shimarrudz commented on src/components/LandingPage/index.tsx
> +import imgHome from "../../app/assets/img/imagem-site.png";
Aplicar path maping em todos os imports

2023-07-31 21:21 UTC, shimarrudz commented on src/components/LandingPage/index.tsx
> +import imgHome from "../../app/assets/img/imagem-site.png";
Acho export barrel interessante de ser aplicado aqui tambem

2023-08-01 21:15 UTC, shimarrudz requested changes

2023-08-01 21:15 UTC, shimarrudz commented on .storybook/preview.ts
> +import "../src/styles/tailwind.css";
Implementar path maping

2023-08-01 21:15 UTC, shimarrudz commented on src/app/page.tsx
Voce tirou o path maping aqui

2023-08-01 21:15 UTC, shimarrudz commented on src/components/Button/Intro.mdx
> +import * as Story from "./Button.stories.tsx";
Implementar path maping

2023-08-01 21:15 UTC, shimarrudz commented on src/components/LandingPage/Header/Header.spec.tsx
Eu mudaria a identação deste teste, é algo simples, mas aprendi que ajuda na legibilidade do código é uma boa prática ex:

describe("Header", () => {
  it("should be able to render correctly", () => {
    render(<Header />);

    const image = screen.getByRole("img", { name: "Logo do Grupo GCB" });
    const span = screen.getByText("Expensive Tracker");
    
    expect(image).toBeInTheDocument();
    expect(span).toBeInTheDocument();
  });
});

2023-08-01 21:15 UTC, shimarrudz commented on src/components/LandingPage/LandingPage.spec.tsx
Faria a identação dos testes como falei acima, essa identação é correta nos testes do backend, se for diferente no front peço desculpas pelo review errado

2023-08-01 21:15 UTC, shimarrudz commented on src/components/LandingPage/index.tsx
> +import "react-toastify/dist/ReactToastify.css";
Este import deve ficar nos imports de baixo

2023-08-02 10:35 UTC, Kayke-Fujinaka commented on .storybook/main.ts
> +import path from "path";
`node:path`

O padrão que o Node.js está estabelecendo é de colocar o `node:` nos módulos internos dele para diferenciar e não ocorrer algum problema com um lib de mesmo nome.

2023-08-02 10:38 UTC, Kayke-Fujinaka commented on .storybook/main.ts
> +  },
Deu aulas nessa questão do path mapping no storybook!!!

2023-08-02 10:57 UTC, charlenefialho commented on .storybook/preview.ts
> +import "../src/styles/tailwind.css";
nesse caso não consigo implementar o path mapping

2023-08-02 11:06 UTC, Kayke-Fujinaka requested changes

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on .storybook/preview.ts
> +};
Esse seria um laptop

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on package.json
>      "next": "13.4.12",
Arrumas as dependências que tem umas que deviam estar em dependência que irão subir para produção.

```
"dependencies": {
  "@auth0/nextjs-auth0": "^3.0.0-beta.3",
  "@hookform/resolvers": "^3.1.1",
  "@reduxjs/toolkit": "^1.9.5",
  "axios": "^1.4.0",
  "next": "13.4.12",
  "phosphor-react": "^1.4.1",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "react-hook-form": "^7.45.2",
  "react-router-dom": "^6.14.2",
  "react-toastify": "^9.1.3",
  "tailwind-merge": "^1.14.0",
  "tailwindcss": "3.3.3"
}
```

```
"devDependencies": {
  "@rocketseat/eslint-config": "^2.1.0",
  "@storybook/addon-essentials": "^7.1.1",
  "@storybook/addon-interactions": "^7.1.1",
  "@storybook/addon-links": "^7.1.1",
  "@storybook/addon-onboarding": "^1.0.8",
  "@storybook/addon-styling": "^1.3.4",
  "@storybook/blocks": "^7.1.1",
  "@storybook/nextjs": "^7.1.1",
  "@storybook/react": "^7.1.1",
  "@storybook/testing-library": "^0.2.0",
  "@testing-library/jest-dom": "^5.17.0",
  "@testing-library/react": "^14.0.0",
  "@types/node": "20.4.4",
  "@types/react": "18.2.16",
  "@types/react-dom": "18.2.7",
  "autoprefixer": "^10.4.14",
  "eslint": "^8.45.0",
  "eslint-config-next": "13.4.12",
  "eslint-plugin-jest-dom": "^5.0.1",
  "eslint-plugin-testing-library": "^5.11.0",
  "jest": "^29.6.1",
  "jest-environment-jsdom": "^29.6.1",
  "postcss": "^8.4.27",
  "storybook": "^7.1.1",
  "ts-jest": "^29.1.1",
  "ts-node": "^10.9.1",
  "typescript": "5.1.6"
}
```

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/styles/tailwind.css
> +}
Arruma a identação.

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +      toast.error("Ocorreu um erro durante o redirecionamento: ");
Tira esses dois pontos e deixa assim "Ocorreu um erro durante o redirecionamento."

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +import "react-toastify/dist/ReactToastify.css";
Isso!

Arrumar os imports.

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +    } catch (error) {
Você não está colocando a mensagem de error então pode tirar o `(error)`

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +      window.location.href = "/api/auth/login";
Ao invés de utilizar o window tenta colocar o router ou navigate.

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +  const [isLoading, setIsLoading] = useState(false);
`const [isLoading, setIsLoading] = useState<boolean>(false);`

Tipar os estados.

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.stories.tsx
> +export const Laptop: StoryObj = {
LaptopLarge

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.stories.tsx
> +export const Desktop: StoryObj = {
Laptop

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/app/page.tsx
Tirou o path mapping?

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/Header.stories.tsx
> +export const Desktop: StoryObj = {
Laptop

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/Header/Header.stories.tsx
> +export const Laptop: StoryObj = {
LaptopLarge

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.spec.tsx
> +  });
Você já testou isso encima.

2023-08-02 11:06 UTC, Kayke-Fujinaka commented on src/components/LandingPage/LandingPage.spec.tsx
> +  });
Não testou redirect nenhum aqui.

2023-08-02 14:56 UTC, LuKezLima commented on src/components/LandingPage/index.tsx
> +  const [isLoading, setIsLoading] = useState(false);
Só uma observação mesmo, apesar da nomenclatura isLoading ser comum de encontrar, ela é genérica e n diz muito para o dev qual o contexto do loading, por exemplo, se nesse contexto ela se chamasse isRedirectingToLogin, ficaria mais rápido pro dev identificar a funcionalidade dela. Isso claro, se ela n for utilizada em outros lugares.

2023-08-02 20:06 UTC, Kayke-Fujinaka approved these changes

2023-08-02 20:06 UTC, Kayke-Fujinaka commented on .storybook/preview.ts
>    styles: {
Deixar na ordem de resolução.

2023-08-02 20:49 UTC, merged