feat/login-flow-and-authenticate-with-auth0
Grupo-GCB/expense-tracker-portal pull request #6
Opened 2023-07-29 02:44 UTC by AugustoCVS

# Descrição da tarefa

Neste PR realizamos a integração do sistema de login e autentificação do auth0 na aplicação, pegando os dados da sessão do usuário e a apresentação de um dado do usuário na tela depois do login

Solicitante(s) da tarefa

- Kayke Fujinaka

Card(s) da tarefa

- Implementar login no Frontend / https://dev.azure.com/GCBInvestimentos/Academy%202.0/_backlogs/backlog/Academy%202.0%20Team/Epics/?workitem=22291

- Apresentação do dado na tela / https://dev.azure.com/GCBInvestimentos/Academy%202.0/_backlogs/backlog/Academy%202.0%20Team/Epics/?workitem=22393

# Checklist

Você realizou o code review do seu próprio PR?

- [X] Sim
- [ ] Não

---

Necessário seguir alguma ordem de deploy (ex: aceitar outro PR antes)?

- [ ] Sim
- [X] Não

### Testes que precisa ser realizado para aprovação do PR

- [X] Produtos
- [ ] Ux/Ui
- [ ] QA

Responsáveis pelos testes QA:

- Charlene Fialho

2023-07-29 03:25 UTC, Kayke-Fujinaka requested changes

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on package.json
> +    "axios": "^1.4.0",
Axios deve ser instalada como dependencie.

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on pages/api/sessionAuth.ts
Acho que a mensagem "Something went wrong" poderia ser armazenado em alguma variável para ser compartilhada em outros lugares que terão essa mesma mensagem padrão de erro.

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on src/app/page.tsx
> +  if (isLoading) return <div>Carregando...</div>
Adicionar o Spinner no meio da tela ao invés desse "Carregando..." com a tela branca.

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on src/app/page.tsx
> +  if (error) return <div>{error.message}</div>
Ele vai ficar em uma tela branca com a mensagem no canto superior esquerdo. 

Acho válido deixar no meio da tela formatadinho.

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on tsconfig.json
> +      "module": "es2015",
Coloca o 2020

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on src/components/LandingPage/index.tsx
> +import imgHome from '@/app/assets/img/imagem-site.png'
Muda o nome desse arquivo da imagem para inglês.

2023-07-29 03:25 UTC, Kayke-Fujinaka commented on src/components/Home/index.tsx
> +import { ISession } from '@/interfaces/Session'
Cria o barrel export das interfaces.

2023-07-31 21:31 UTC, shimarrudz requested changes

2023-07-31 21:31 UTC, shimarrudz commented on cypress/e2e/1-getting-started/login.cy.ts
> +    cy.get('p').should('be.visible').contains("Don't have an account?")
Algumas aspas estão simples e outras duplas, acho válido padronizar

2023-07-31 21:31 UTC, shimarrudz commented on cypress/support/e2e.ts
> +// ***********************************************************
Esses comentários influenciam na funcionalidade do código? Se não tiver influencia, ter comentários no código não é uma boa prática, e seria viável aplicar o barrel export no código?

2023-07-31 21:31 UTC, shimarrudz commented on src/components/LandingPage/Header/index.tsx
> +import logo from '@/app/assets/svg/logo.svg'
Aplicar barrel export, se quiser posso te ajudar com isso

2023-07-31 21:31 UTC, shimarrudz commented on src/tests/sessionAuth.spec.tsx
> +import sessionAuth from '../../pages/api/sessionAuth'
Aplicar path maping

2023-07-31 21:31 UTC, shimarrudz commented on src/tests/sessionAuth.spec.tsx
Mandou muito na identação e testes em geral, boa!

2023-08-01 11:31 UTC, AugustoCVS commented on src/components/LandingPage/index.tsx
> +import imgHome from '@/app/assets/img/imagem-site.png'
Charlene resolveu

2023-08-01 17:03 UTC, AugustoCVS commented on src/components/LandingPage/Header/index.tsx
> +import logo from '@/app/assets/svg/logo.svg'
Charlene arrumou

2023-08-01 17:59 UTC, LuKezLima commented on src/interfaces/Session.tsx
> +  token_type: string
Se possível padronizar nomenclatura de tipagem, ou tudo camelCase ou td snake_case

2023-08-01 17:59 UTC, LuKezLima commented on src/interfaces/User.tsx
> +  family_name?: string
Se possível padronizar nomenclatura de tipagem, ou tudo camelCase ou td snake_case

2023-08-01 18:51 UTC, AugustoCVS commented on src/interfaces/Session.tsx
> +  token_type: string
Essa nomenclatura esta vindo diretamente do auth0

2023-08-01 18:52 UTC, AugustoCVS commented on src/interfaces/User.tsx
> +  family_name?: string
Essa nomenclatura esta vindo diretamente do auth0

2023-08-01 21:34 UTC, shimarrudz requested changes

2023-08-01 21:34 UTC, shimarrudz commented on src/tests/sessionAuth.spec.tsx
> +import sessionAuth from '../../pages/api/sessionAuth'
Implementar path maping

2023-08-01 21:34 UTC, shimarrudz commented on src/utils/constants.ts
> +export const DEFAULT_UNKNOWN_ERROR_MESSAGE = 'Something went wrong.'
No backend, o Kayke falou pra seguirmos um padrão onde os erros são em pt-bt, seria legal se seguissemos este padrão no projeto como um todo

2023-08-01 21:34 UTC, shimarrudz commented on src/components/Loading/intro.mdx
> +import * as Story from "./Loading.stories.tsx";
Implementar path maping

2023-08-01 21:34 UTC, shimarrudz commented on src/components/Home/index.tsx
> +        console.error('Axios error:', error.message)
Conferir se é válida a padronização de erros para pt-br igual estamos fazendo no backend (Kayke achou melhor os erros serem tratados em pt-br)

*OBS*: Uma dúvida, nessa function, seria possível utilizar um throw new error? ou apenas o console.log mesmo?

2023-08-01 21:34 UTC, shimarrudz commented on src/components/Error/Intro.mdx
> +import * as Story from "./Error.stories.tsx";
Implementar path maping

2023-08-01 21:34 UTC, shimarrudz commented on package.json
> +  "version": "0.1.1",
Como voce colocou novas libs no projeto, acho legal atualizar a versão do package json

2023-08-01 21:34 UTC, shimarrudz commented on cypress/support/e2e.ts
> +import './commands'
Implementar path maping

2023-08-01 21:34 UTC, shimarrudz commented on .storybook/preview.ts
> +import "../src/styles/tailwind.css";
Implementar o path maping

2023-08-01 22:05 UTC, AugustoCVS commented on src/tests/sessionAuth.spec.tsx
> +import sessionAuth from '../../pages/api/sessionAuth'
Nesse não tem como

2023-08-01 22:05 UTC, AugustoCVS commented on src/components/Loading/intro.mdx
> +import * as Story from "./Loading.stories.tsx";
Nesse não tem como

2023-08-01 22:07 UTC, AugustoCVS commented on src/components/Home/index.tsx
> +        console.error('Axios error:', error.message)
O throw new error não da certo porque o error não entra nos critérios

2023-08-01 22:07 UTC, AugustoCVS commented on src/components/Error/Intro.mdx
> +import * as Story from "./Error.stories.tsx";
esse não tem como

2023-08-01 22:08 UTC, AugustoCVS commented on cypress/support/e2e.ts
> +import './commands'
Esse é do proprio cypress, não tem como

2023-08-01 22:09 UTC, AugustoCVS commented on .storybook/preview.ts
> +import "../src/styles/tailwind.css";
Esse não tem como

2023-08-02 11:31 UTC, Kayke-Fujinaka requested changes

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on .storybook/main.ts
> +import path from "path";
`node:path`

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on .storybook/preview.ts
> +};
Laptop

Seguir os devices do inspencionar

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on package.json
> +  "version": "0.1.1",
Vai dar conflito de versão com a Charlene, então coloca o "0.0.2"

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on pages/api/sessionAuth.ts
> +    console.error('Error obtaining the session:', error)
Dá um espaço na mensagem se não vai ficar colado.

"Error obtaining the session: "

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/app/page.tsx
> +import { Error } from '@/components/Error'
Junta tudo no barrel export.

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/components/Error/Error.stories.tsx
> +import { Error } from '@/components/Error'
Tira o `/Error`

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/components/Error/Error.stories.tsx
> +}
Cria ele no mobile e laptop

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/components/Home/index.tsx
> +      const res = await axios.get<{ userSession: ISession }>('/api/sessionAuth')
Cria uma função para chamar a função.

```
const getUserSession = async (): Promise<ISession> => {
  const res = await axios.get<{ userSession: ISession }>('/api/sessionAuth');
  return res.data.userSession;
};
```

Ai ficaria `const { idToken, accessToken } = await getUserSession();`

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/components/Home/index.tsx
> +      const res = await axios.get<{ userSession: ISession }>('/api/sessionAuth')
No next 13 não sei como funciona a questão de utilizar o serverSideProps, mas dá uma olhadinha para fazer as requisições antes de renderizar a page.

https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/components/Home/index.tsx
> +  }, [])
Aqui ele só vai executar a função quando a página renderizar. 

Caso você queira que assim que alguma variável mudar, você pode colocar:
```
  useEffect(() => {
    handleUserSession();
  }, [handleUserSession]);
```

2023-08-02 11:31 UTC, Kayke-Fujinaka commented on src/components/Home/index.tsx
> +  if (!user) return null
Se o usuário não existir a página ficará em branco, sendo assim, é válido aparecer alguma mensagem de erro (aquela página de erro) ou redirecionar ele para a landing para realizar o login novamente.

2023-08-02 11:54 UTC, cleversonffaria commented on src/tests/sessionAuth.spec.tsx
> +    expect(res.status).toHaveBeenCalledWith(error.status || 500)
não precisa do "OU" o "error" sempre vai existir pq vc esta especificando ele acima.

2023-08-02 12:55 UTC, AugustoCVS commented on src/components/Home/index.tsx
> +      const res = await axios.get<{ userSession: ISession }>('/api/sessionAuth')
Ainda to pesquisando certinho, mas aparentemente o getServerSideProps não é mais necessário no pasta app, acho que não é nem mais suportado, mas ainda to pesquisando pra confirmar

2023-08-02 13:53 UTC, Kayke-Fujinaka commented on .storybook/preview.ts
> +};
Deixa isso na ordem das resoluções, mas só por conta de toque.

2023-08-02 13:56 UTC, AugustoCVS commented on .storybook/preview.ts
> +};
Beleza

2023-08-02 14:07 UTC, Kayke-Fujinaka approved these changes

2023-08-02 14:20 UTC, Diogo-gallina approved these changes

2023-08-02 14:21 UTC, shimarrudz approved these changes

2023-08-02 16:45 UTC, merged